import { useMemo, useState } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import './game.css'
import './cinematic.css'

const themeStories = {
  'Treasure Hunt': { title: 'The Lost Royal Seal', intro: 'A royal seal vanished beneath Pune’s old city. Follow the clues, gather the five fragments, and keep it from the Shadow Cartographer.', accent: 'gold' },
  'Detective Mystery': { title: 'The Case of the Vanishing Map', intro: 'An archive map disappeared from a locked room. Read the city’s details, question its guardians, and expose the thief before dusk.', accent: 'violet' },
  'Fantasy Kingdom': { title: 'The Compass of Suryanagar', intro: 'The Crystal Compass has awakened. Recover its scattered pieces before an ancient shadow turns the streets to stone.', accent: 'mint' },
}

const missionSeed = [
  { id: 1, title: 'The Guardian’s Watch', kind: 'Landmark', icon: '⌂', place: 'Shaniwar Wada', detail: 'Reach the eastern gate and look for the sun-shaped carving above the arch.', xp: 120, coins: 30, time: '20 min', hint: 'The main entrance is busy. The eastern arch is quieter and faces the old market.', reward: 'Bronze gate key' },
  { id: 2, title: 'A Doorway Through Time', kind: 'Photo quest', icon: '◈', place: 'Kasba Peth', detail: 'Photograph an old doorway with a carved floral pattern. The image is your proof.', xp: 180, coins: 45, time: '35 min', hint: 'Explore the narrow lanes near the temple; look at eye level, not the rooftops.', reward: 'Timeworn lens' },
  { id: 3, title: 'Whispers of the Peshwas', kind: 'History riddle', icon: '?', place: 'Shaniwar Wada', detail: 'Solve the clue: “I have five gates, but one carries the name of a god. Which am I?”', xp: 250, coins: 60, time: '15 min', hint: 'Think of the gate associated with Ganesha. A local guide can confirm the answer.', reward: 'Seal fragment' },
  { id: 4, title: 'The Merchant’s Brew', kind: 'Local find', icon: '☕', place: 'Camp', detail: 'Find a café where the menu lists a drink named after a monsoon season.', xp: 150, coins: 40, time: '30 min', hint: 'Search local café menus nearby and ask for their seasonal specials.', reward: 'Merchant token' },
]

function ProgressRing({ value }) { return <div className="progress-ring" style={{ '--progress': `${value * 3.6}deg` }}><span>{value}%</span></div> }

export default function App() {
  const [stage, setStage] = useState('landing')
  const [hero, setHero] = useState({ name: 'Manaswini', avatar: '✦', role: 'Historian' })
  const [form, setForm] = useState({ destination: 'Pune, India', theme: 'Treasure Hunt', duration: '4 hours', difficulty: 'Medium', budget: '₹1,000 – ₹2,000', travelType: 'Solo', interests: ['History', 'Photography'] })
  const [missions, setMissions] = useState(missionSeed.map((m, i) => ({ ...m, status: i === 0 ? 'active' : 'locked' })))
  const [selected, setSelected] = useState(1)
  const [hintLevel, setHintLevel] = useState(0)
  const [toast, setToast] = useState('')
  const [sidePanel, setSidePanel] = useState('inventory')
  const [companionOpen, setCompanionOpen] = useState(false)
  const story = themeStories[form.theme]
  const completed = missions.filter(m => m.status === 'done')
  const active = missions.find(m => m.status === 'active')
  const progress = Math.round((completed.length / missions.length) * 100)
  const xp = 640 + completed.reduce((sum, m) => sum + m.xp, 0)
  const coins = 90 + completed.reduce((sum, m) => sum + m.coins, 0)
  const selectedMission = missions.find(m => m.id === selected) || active

  const toggleInterest = (interest) => setForm(state => ({ ...state, interests: state.interests.includes(interest) ? state.interests.filter(i => i !== interest) : [...state.interests, interest] }))
  const launch = () => { setStage('adventure'); setToast(`${hero.name}, your AI Game Master has prepared the first clue.`); window.setTimeout(() => setToast(''), 3000) }
  const completeMission = (id) => {
    const mission = missions.find(m => m.id === id)
    if (!mission || mission.status !== 'active') return
    setMissions(items => items.map(item => item.id === id ? { ...item, status: 'done' } : item.id === id + 1 ? { ...item, status: 'active' } : item))
    setSelected(id + 1 <= missions.length ? id + 1 : id)
    setHintLevel(0)
    setToast(`Quest complete! +${mission.xp} XP and ${mission.coins} coins earned.`)
    if (id === missions.length) window.setTimeout(() => setStage('boss'), 800)
    window.setTimeout(() => setToast(''), 3600)
  }
  const reset = () => { setMissions(missionSeed.map((m, i) => ({ ...m, status: i === 0 ? 'active' : 'locked' }))); setSelected(1); setHintLevel(0); setStage('landing') }
  const panelContent = useMemo(() => sidePanel === 'inventory' ? completed.length ? completed.map(m => <div className="loot" key={m.id}><span>{m.icon}</span><div><b>{m.reward}</b><small>From {m.title}</small></div></div>) : <p className="empty-state">Your discoveries will appear here after you complete a quest.</p> : <div className="badges"><div><span>⌂</span><b>Pathfinder</b><small>Finish a landmark quest</small></div><div className={completed.length >= 2 ? '' : 'muted'}><span>◈</span><b>Story Collector</b><small>Complete 2 quests</small></div><div className={progress === 100 ? '' : 'muted'}><span>♛</span><b>City Legend</b><small>Complete the adventure</small></div></div>, [sidePanel, completed, progress])

  return <div className="adventure-app">
    <header className="adventure-nav"><a className="quest-brand" href="#top"><i>✦</i>Wander<span>Quest</span></a><div className="nav-route"><span>AI ADVENTURE GENERATOR</span><b>•</b><span>{stage === 'setup' ? 'CREATE AN ADVENTURE' : form.destination.toUpperCase()}</span></div>{stage === 'adventure' && <div className="player-stats"><span>LVL 4</span><div><i style={{ width: `${Math.min(92, 35 + progress / 2)}%` }}></i></div><b>{xp} XP</b><strong>◉ {coins}</strong></div>}</header>
    <AnimatePresence mode="wait">{stage === 'landing' ? <motion.main className="landing-page" key="landing" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}><div className="landing-scene"><span className="landing-star">✦</span><p className="kicker">EVERY JOURNEY BECOMES A STORY</p><h1>THE CITY IS<br/><em>WAITING.</em></h1><p>Step into a live adventure where every landmark has a secret, every choice changes the story, and you are the hero.</p><motion.button whileHover={{scale:1.03}} whileTap={{scale:.97}} className="begin-button" onClick={() => setStage('character')}>Begin adventure <span>→</span></motion.button><small>AI GAME MASTER · LOCATION QUESTS · REAL-WORLD REWARDS</small></div></motion.main> : stage === 'character' ? <motion.main className="character-page" key="character" initial={{opacity:0,x:20}} animate={{opacity:1,x:0}} exit={{opacity:0,x:-20}}><div className="character-card"><p className="kicker">STEP 01 OF 02 · CREATE YOUR ADVENTURER</p><h1>Who enters<br/><em>the story?</em></h1><label className="field-label">ADVENTURER NAME<input value={hero.name} onChange={e => setHero({...hero,name:e.target.value})}/></label><p className="field-label">CHOOSE A CLASS</p><div className="class-grid">{[['Explorer','⌖'],['Historian','▤'],['Photographer','◈'],['Food Detective','☕']].map(([role,icon]) => <button key={role} onClick={() => setHero({...hero,role,avatar:icon})} className={hero.role === role ? 'chosen' : ''}><span>{icon}</span><b>{role}</b><small>{role === 'Historian' ? 'Story puzzles & relics' : role === 'Photographer' ? 'Scenic clues & photo quests' : role === 'Food Detective' ? 'Secret menus & local finds' : 'Hidden routes & discoveries'}</small></button>)}</div><div className="hero-preview"><span>{hero.avatar}</span><div><b>{hero.name || 'Unknown adventurer'}</b><small>{hero.role}</small></div></div><motion.button whileTap={{scale:.98}} className="launch-button" onClick={() => setStage('setup')}>Continue to adventure builder <span>→</span></motion.button></div></motion.main> : stage === 'setup' ? <motion.main className="setup-page" key="setup" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0,y:-12}}>
      <section className="setup-intro"><p className="kicker">YOUR CITY. YOUR STORY.</p><h1>TURN THE WORLD INTO<br/><em>YOUR ADVENTURE.</em></h1><p>Pick a destination and mood. Your AI Game Master will turn nearby places into a playable quest trail.</p><div className="mini-points"><span>✦ Personal story</span><span>⌖ Local discoveries</span><span>♛ Real rewards</span></div></section>
      <section className="creator-card"><div className="creator-head"><div><p className="kicker">STEP 01 OF 01</p><h2>Build your quest</h2></div><span className="creator-mark">✦</span></div><label className="field-label">DESTINATION<input value={form.destination} onChange={e => setForm({...form,destination:e.target.value})} /></label><div className="field-row"><label className="field-label">TRIP DURATION<select value={form.duration} onChange={e => setForm({...form,duration:e.target.value})}><option>2 hours</option><option>4 hours</option><option>Full day</option></select></label><label className="field-label">DIFFICULTY<select value={form.difficulty} onChange={e => setForm({...form,difficulty:e.target.value})}><option>Easy</option><option>Medium</option><option>Hard</option></select></label></div><p className="field-label">CHOOSE A THEME</p><div className="theme-picker">{Object.keys(themeStories).map(theme => <button onClick={() => setForm({...form,theme})} className={form.theme === theme ? 'chosen' : ''} key={theme}><span>{theme === 'Treasure Hunt' ? '⌘' : theme === 'Detective Mystery' ? '◐' : '✧'}</span>{theme}</button>)}</div><p className="field-label">WHAT DO YOU LIKE?</p><div className="interest-picker">{['History','Photography','Food','Nature','Mystery','Art'].map(item => <button onClick={() => toggleInterest(item)} className={form.interests.includes(item) ? 'selected' : ''} key={item}>{form.interests.includes(item) ? '✓ ' : ''}{item}</button>)}</div><motion.button whileTap={{scale:.98}} className="launch-button" onClick={launch}>Generate my adventure <span>→</span></motion.button></section>
    </motion.main> : stage === 'boss' ? <motion.main className="boss-page" key="boss" initial={{opacity:0,scale:.96}} animate={{opacity:1,scale:1}} exit={{opacity:0}}><section className="boss-card"><p className="kicker">FINAL CHAPTER · THE SHADOW CARTOGRAPHER</p><span className="boss-mark">♛</span><h1>The seal is<br/><em>within reach.</em></h1><p>{hero.name}, the Shadow Cartographer offers one final riddle: “I chart every path, but I never take a step. What am I?”</p><div className="boss-answers"><button onClick={() => setStage('ending')}>A map</button><button onClick={() => setToast('The shadow laughs. Try another answer.')}>A compass</button><button onClick={() => setToast('Not quite. Listen to the words of the riddle.')}>A traveler</button></div></section></motion.main> : stage === 'ending' ? <motion.main className="ending-page" key="ending" initial={{opacity:0}} animate={{opacity:1}}><section><p className="kicker">LEGEND ENDING UNLOCKED</p><span>✦</span><h1>The Royal Seal<br/>is restored.</h1><p>You completed every trail, trusted your instincts, and returned the lost seal to the old city. Pune will remember your name, {hero.name}.</p><div><b>+500 XP</b><b>Legendary · Royal Seal</b></div><button className="launch-button" onClick={reset}>Begin another story <span>→</span></button></section></motion.main> : <motion.main className="play-page" key="adventure" initial={{opacity:0,y:12}} animate={{opacity:1,y:0}} exit={{opacity:0}}>
      <section className={`story-hero ${story.accent}`}><div className="hero-text"><p className="kicker">CHAPTER 1 · THE OLD CITY</p><h1>{story.title}</h1><p>{story.intro}</p><div><span>⌖ {form.destination}</span><span>◷ {form.duration}</span><span>⚡ {form.difficulty}</span></div></div><div className="hero-illustration"><div className="sun"></div><div className="hills"></div><div className="cityline"><i></i><i></i><i></i><i></i><i></i></div><b>✦</b></div><div className="chapter-progress"><ProgressRing value={progress}/><div><span>ADVENTURE PROGRESS</span><b>{completed.length} of {missions.length} quests</b></div></div></section>
      <div className="play-grid"><section className="mission-area"><div className="section-title"><div><p className="kicker">YOUR QUEST TRAIL</p><h2>Choose your next move</h2></div><button onClick={() => setHintLevel(level => Math.min(2, level + 1))}>Need a hint? <span>↗</span></button></div><div className="mission-track">{missions.map((mission, index) => <motion.button key={mission.id} className={`mission-card ${mission.status} ${selected === mission.id ? 'viewing' : ''}`} onClick={() => { if (mission.status !== 'locked') { setSelected(mission.id); setHintLevel(0) } }} whileHover={mission.status !== 'locked' ? {y:-3} : {}}><span className="mission-order">{mission.status === 'done' ? '✓' : `0${index + 1}`}</span><span className="mission-icon">{mission.icon}</span><span className="mission-copy"><small>{mission.kind}</small><b>{mission.title}</b><em>{mission.place}</em></span><span className="mission-reward">+{mission.xp} XP<br/><i>{mission.time}</i></span><span className="mission-status">{mission.status === 'locked' ? '⌁' : '›'}</span></motion.button>)}</div></section>
      <aside className="game-sidebar"><section className="map-box"><div className="map-top"><div><p className="kicker">LIVE QUEST MAP</p><h3>Old city trail</h3></div><span>⌖</span></div><div className="map-canvas"><i className="river"></i><i className="road one"></i><i className="road two"></i>{missions.map(m => <button key={m.id} aria-label={m.title} onClick={() => m.status !== 'locked' && setSelected(m.id)} className={`map-pin pin-${m.id} ${m.status}`}>{m.status === 'done' ? '✓' : m.status === 'locked' ? '⌁' : '✦'}</button>)}<span className="location-dot"></span><small className="map-tag">You are here</small></div></section><section className="side-tabs"><div><button onClick={() => setSidePanel('inventory')} className={sidePanel === 'inventory' ? 'active' : ''}>Inventory</button><button onClick={() => setSidePanel('badges')} className={sidePanel === 'badges' ? 'active' : ''}>Badges</button></div>{panelContent}</section></aside></div>
      {selectedMission && <section className="mission-drawer"><div className="drawer-symbol">{selectedMission.icon}</div><div className="drawer-copy"><p className="kicker">{selectedMission.status === 'done' ? 'QUEST COMPLETE' : selectedMission.kind.toUpperCase()}</p><h2>{selectedMission.title}</h2><p>{selectedMission.detail}</p>{hintLevel > 0 && selectedMission.status === 'active' && <div className="hint-box"><b>ARIA’S HINT · {hintLevel === 1 ? 'GENTLE NUDGE' : 'CLEAR DIRECTION'}</b><p>{hintLevel === 1 ? selectedMission.hint.split('. ')[0] + '.' : selectedMission.hint}</p></div>}</div><div className="drawer-actions">{selectedMission.status === 'active' && <><button className="hint-button" onClick={() => setHintLevel(level => Math.min(2, level + 1))}>✦ Hint {hintLevel ? `(${hintLevel}/2)` : ''}</button><motion.button whileTap={{scale:.97}} className="complete-button" onClick={() => completeMission(selectedMission.id)}>Mark complete <span>✓</span></motion.button></>}{selectedMission.status === 'done' && <span className="done-label">✓ Completed</span>}{selectedMission.status === 'locked' && <span className="locked-label">⌁ Complete the previous quest</span>}</div></section>}
      <button className="companion-button" onClick={() => setCompanionOpen(open => !open)}>✦ Ask Aria <span>{companionOpen ? '×' : '↗'}</span></button>{companionOpen && <motion.section className="companion-panel" initial={{opacity:0,y:12}} animate={{opacity:1,y:0}}><div><span>✦</span><b>Aria, the Archivist</b><small>AI companion · {hero.role}</small></div><p>{active ? `“${hero.name}, ${active.hint} Would you like a hint, or do you want to trust your instincts?”` : '“You have found every fragment. The Shadow Cartographer is waiting for you.”'}</p><div><button onClick={() => { setHintLevel(2); setCompanionOpen(false) }}>Show a hint</button><button onClick={() => setToast('Aria says: Your choices are shaping a legend.')}>Ask about the story</button></div></motion.section>}<button className="new-adventure" onClick={reset}>← Create a different adventure</button>
    </motion.main>}</AnimatePresence>{toast && <motion.div className="game-toast" initial={{opacity:0,y:15}} animate={{opacity:1,y:0}} exit={{opacity:0,y:10}}>✦ {toast}</motion.div>}</div>
}
